markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
collections:
  docs:
    output: true
    permalink: '/:collection/:path/'

gems:
  - jekyll-redirect-from
